# Generated by Django 5.0.6 on 2026-05-22 11:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('budget_cr', models.IntegerField(default=0)),
                ('scheme_primary', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('division', models.CharField(choices=[('bastar', 'Bastar'), ('bilaspur', 'Bilaspur'), ('durg', 'Durg'), ('raipur', 'Raipur'), ('surguja', 'Surguja')], max_length=20)),
                ('lwe', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('finance_secretary', 'Finance Secretary'), ('collector', 'District Collector'), ('dept_head', 'Department Head'), ('dpo', 'District Programme Officer'), ('ee', 'Executive Engineer'), ('ddo', 'Drawing & Disbursing Officer'), ('je', 'Junior Engineer')], default='je', max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='projects.department')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='projects.district')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('scheme', models.CharField(choices=[('NHM', 'National Health Mission'), ('PMGSY', 'PM Gram Sadak Yojana'), ('JJM', 'Jal Jeevan Mission'), ('PMKSY', 'PM Krishi Sinchai Yojana'), ('AMRUT', 'AMRUT 2.0'), ('15FC', '15th Finance Commission'), ('SAMAGRA', 'Samagra Shiksha'), ('STATE', 'State Scheme'), ('OTHER', 'Other')], max_length=20)),
                ('funding_model', models.CharField(choices=[('100_centre', '100% Centre'), ('90_10', '90:10 Centre:State'), ('60_40', '60:40 Centre:State'), ('50_50', '50:50 Centre:State'), ('100_state', '100% State')], default='60_40', max_length=20)),
                ('budget_lakhs', models.IntegerField(default=0)),
                ('released_lakhs', models.IntegerField(default=0)),
                ('spent_lakhs', models.IntegerField(default=0)),
                ('current_stage', models.CharField(choices=[('need', 'Need Identified'), ('dpr', 'DPR Prepared'), ('admin', 'Admin Approval'), ('tender', 'Tender Issued'), ('wo', 'Work Order'), ('execution', 'Execution'), ('milestone', '50% Milestone'), ('capex', 'CapEx Booked'), ('uc', 'Completion & UC')], default='need', max_length=20)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('delayed', 'Delayed'), ('critical', 'Critical'), ('complete', 'Complete')], default='on_track', max_length=20)),
                ('physical_pct', models.IntegerField(default=0)),
                ('capex_due', models.DateField(blank=True, null=True)),
                ('contractor', models.CharField(blank=True, default='Not yet awarded', max_length=200)),
                ('work_order_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assigned_je', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.department')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.district')),
            ],
            options={
                'ordering': ['capex_due', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('physical_pct', models.IntegerField()),
                ('remark', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='milestones/%Y/%m/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('issue_flag', models.BooleanField(default=False)),
                ('issue_type', models.CharField(blank=True, choices=[('contractor', 'Contractor'), ('material', 'Material'), ('land', 'Land Acquisition'), ('fund', 'Fund Release'), ('security', 'Security/LWE'), ('other', 'Other')], max_length=50)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_trail', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trail', to='projects.project')),
            ],
            options={
                'ordering': ['-logged_at'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('capex_30d', 'CapEx due in 30 days'), ('capex_15d', 'CapEx due in 15 days'), ('capex_7d', 'CapEx due in 7 days'), ('capex_od', 'CapEx overdue'), ('stage_stuck', 'Stage stuck >30 days'), ('no_update', 'No update in 14 days')], max_length=20)),
                ('message', models.TextField()),
                ('days_left', models.IntegerField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='projects.project')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='StageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('need', 'Need Identified'), ('dpr', 'DPR Prepared'), ('admin', 'Admin Approval'), ('tender', 'Tender Issued'), ('wo', 'Work Order'), ('execution', 'Execution'), ('milestone', '50% Milestone'), ('capex', 'CapEx Booked'), ('uc', 'Completion & UC')], max_length=20)),
                ('stage_date', models.DateField()),
                ('done_by_name', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('voucher_ref', models.CharField(blank=True, max_length=100)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='projects.project')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['logged_at'],
            },
        ),
    ]
